####
# Drone.io standard template for 1Day microservices
# Required secrets: docker_username, docker_password
####

pipeline:

  prepare:
    image: node:10
    commands:
      - yarn install
  test:
    image: node:10
    commands:
      - yarn run lint
      - yarn run test
  build:
    image: node:10
    commands:
      - yarn run build
      - yarn install --production

  generate_tags:
    image: docker.1day.host/1day/drone-generate-docker-tags:latest

  publish:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: docker.1day.host/1day/${DRONE_REPO_NAME}
    registry: https://docker.1day.host
  webhook:
    image: plugins/webhook
    networks:
      - app_net
    urls: http://ops_microservice-deployment/api/notify/build
    content_type: application/json
    template: |
      {
        "repo_name": "${DRONE_REPO_NAME}",
        "build_event": "${DRONE_BUILD_EVENT}",
        "build_number": "${DRONE_BUILD_NUMBER}",
        "tag": "${DRONE_TAG}",
        "branch": "${DRONE_BRANCH}",
        "commit": "${DRONE_COMMIT}"
      }
  slack:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: deployments
    template: >
      {{#success build.status}}
        *Success*: {{build.author}}'s build <{{build.link}}|{{build.number}}> in {{repo.name}} on branch {{build.branch}}.
        *Good job!*
      {{else}}
        *Fail*: {{build.author}}'s build <{{build.link}}|{{build.number}}> in {{repo.name}} on branch {{build.branch}}.
        *Please fix!*
      {{/success}}

networks: 
  app_net:
    external: true