swarm-sync:
  stacks:
    - nonprod
  updateInterval: 60000
  git:
    url: https://github.com/kevb/swarm-sync-example
    branch: master
  #gitCrypt:
  #  keyFile: /run/secrets/git-crypt-key
  docker:
    host: unix:///var/run/docker.sock
    socketPath: /var/run/docker.sock
