swarm-sync:
  stack: experimental
  git:
    url: https://github.com/kevb/swarm-sync-example
    branch: master
    updateInterval: 60000
  #gitCrypt:
  #  keyFile: /run/secrets/git-crypt-key
  docker:
    host: unix:///var/run/docker.sock
    socketPath: /var/run/docker.sock
    updateInterval: 40000
