swarm-sync:

  # Stacks in target for this swarm-sync instance
  stacks:
    - nonprod

  # Update frequency for polling repo and image registry for changes (ms)
  # Below 1 minute not recommended
  updateInterval: 60000

  # Git details for your Swarm Configuration Repository
  git:
    url: https://github.com/mrflutters/swarm-sync-example
    branch: master

  # Common config with swarm-pack
  docker:
    socketPath: /var/run/docker.sock
    # used for throttling time between Docker registry requests
    minRegistryReqInterval: 2000

  # swarm-pack repos
  repositories:
    - name: official
      url: https://github.com/swarm-pack/repository